### ISSUE TITLE
'allocate' parameter may not correct in the documentation

### ISSUE THREAD

**Issue by Sakib37** [openbaton/docs#6]
Hi,

In the documentation it is mentioned that the meaning of the 'allocate' parameter is 
(1) "true if the NFVO will ALLOCATE_RESOURCES, false if the VNFManager will do"
but actually it should be opposite
(2) "false if the NFVO will ALLOCATE_RESOURCES, true if the VNFManager will do"

(2) worked for me. So I think (2) is correct. Can you please confirm?

**Comment by gc4rella** [comment]
Thx for the hint. yes, we'll update the docs.
